Add index accessor to TSObjectType
omochi/TypeScriptAST pull request #20
Opened 2022-12-22 07:47 UTC by sidepelican

#18 の拡張です。先に#18を見てください。

下記のようなインデックスアクセスを定義できるようにします。
これはMappedTypeとは異なり、ObjectTypeに普通のフィールドと同じように並べて書くことが出来ます。キーの型に重なる部分がなければ複数定義も可能です

```ts
type F = { 
    [k: symbol]: number;
    [k: string]: number;
    0: number;
};
```

2022-12-22 16:19 UTC, omochi requested changes
実装していただいた `TSObjectType.Field` の `case` として追加する方針が良いと思います。

一応きれいなdiffでみたいので、#18 のマージに追従をお願いします。

2022-12-23 03:53 UTC, sidepelican commented on Tests/TypeScriptASTTests/PrintTypeTests.swift
> -            "{ [key: string]: A; }"
IndexAccessorが定義できればTSDictionaryTypeは不要だということに気づいたので、TSDictionaryTypeは削除します

2022-12-23 04:24 UTC, omochi requested changes
方針良いと思います。
`TSDictionaryType` の削除も賛成です。
C2TSで必要だったので、とりあえずこの形だけ表現できるように実装していました。

IndexKind は表現能力が足りていないようなのでコメントしました。

2022-12-23 04:24 UTC, omochi commented on Sources/ASTNodeModule/Decl/TSIndexDecl.swift
> +        case symbol
ここ気になって調べました。

> Only some types are allowed for index signature properties: string, number, symbol, template string patterns, and union types consisting only of these.

https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures

実際playgroundで確認したところ以下はコンパイルできるようでした。

```ts
type A = {
    [key: string | number]: number;
};
```

unionによる組み合わせを考えると列挙しきるのは難しいので、
ここは enum にせず `any TSType` で良いのではないでしょうか

2022-12-23 04:37 UTC, sidepelican commented on Sources/ASTNodeModule/Decl/TSIndexDecl.swift
> +        case symbol
うお〜、unionの考慮を忘れていました。

```ts
type A = number;
class C {
    [k: A]: number;
}
```
これも許されるようですし、`any TSType`のほうが良さそうですね

2022-12-23 04:51 UTC, sidepelican commented
@omochi 指摘事項に対応しました。

2022-12-23 04:55 UTC, omochi commented
ありがとうございました！

2022-12-23 04:55 UTC, merged